name: m3_lightmeter_resources
description: Common resources used by m3_lightmeter and related repositories.
version: 1.3.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test_coverage_badge: ^0.2.0

flutter:
